/*:
 # Table of Contents
 
 - [Constants and Variables](Constants%20and%20Variables)
 - [Control Flow](Control%20Flow)
 - [Optionals](Optionals)
 - [Functions](Functions)
 - [Tuples](Tuples)
 - [Structures](Structures)
 - [Enumerations](Enumerations)
 - [Classes](Classes)
 - [Optional Chaining](Optional%20Chaining)
 - [Closures](Closures)
 - [Type Casting](Type%20Casting)
 - [Protocols](Protocols)
 - [Extensions](Extensions)
 - [Errors](Errors)
 - [Generics](Generics)
 - [Associated Types](Associated%20Types)
 - [Opaque Types](Opaque%20Types)
 - [Ownership](Ownership)
 - [Operators](Operators)
 - [Metatypes](Metatypes)
 - [Access Control](Access%20Control)
 - [Attributes](Attributes)
 - [Property Wrappers](Property%20Wrappers)
 - [Result Builders](Result%20Builders)
 - [Checking API Availability](Checking%20API%20Availability)
 - [Miscellaneous](Miscellaneous)
 - [Concurrency](Concurrency)
 - [Numbers, Bool and Time](Numbers,%20Bool%20and%20Time)
 - [String](String)
 - [Ranges](Ranges)
 - [SetAlgebra](SetAlgebra)
 - [Able Protocols](Able%20Protocols)
 - [Sequences](Sequences)
 - [Collections](Collections)
 - [Expressible By Protocols](Expressible%20By%20Protocols)
 - [String Convertible Protocols](String%20Convertible%20Protocols)
 - [Reflection](Reflection)
 - [Stream And Print](Stream%20And%20Print)
 - [Memory Layout](Memory%20Layout)
 - [Pointers](Pointers)
 - [Codable](Codable)
 - [Observation](Observation)
 - [Regex](Regex)
 - [Regex Syntax Examples](Regex%20Syntax%20Examples)
 - [Copy-on-write](Copy-on-write)
 - [Type-erasing wrappers](Type-erasing%20wrappers)
 - [Interoperability](Interoperability)
 ****
 [Next](@next)
 */
