//: [Previous](@previous)

//: # Types

/*:
 ## Types
 
 * AnyBidirectionalCollection
 * AnyCollection
 * AnyIndex
 * AnyIterator
 * AnyRandomAccessCollection
 * AnySequence
 * Array
 * ArraySlice
 * AutoreleasingUnsafeMutablePointer
 * BidirectionalSlice
 * Bool
 * CVaListPointer
 * Character
 * ClosedRange
 * ClosedRangeIndex
 * ClosedRangeIterator
 * CodeUnit
 * CollectionOfOne
 * ContiguousArray
 * CountableClosedRange
 * CountableRange
 * DefaultBidirectionalIndices
 * DefaultIndices
 * DefaultRandomAccessIndices
 * Dictionary
 * DictionaryIndex
 * DictionaryIterator
 * DictionaryLiteral
 * Double
 * EmptyCollection
 * EmptyIterator
 * EnumeratedIterator
 * EnumeratedSequence
 * FlattenBidirectionalCollection
 * FlattenBidirectionalCollectionIndex
 * FlattenCollection
 * FlattenCollectionIndex
 * FlattenIterator
 * FlattenSequence
 * Float
 * Float80
 * FloatingPointClassification
 * FloatingPointSign
 * ImplicitlyUnwrappedOptional
 * IndexingIterator
 * Int
 * Int16
 * Int32
 * Int64
 * Int8
 * IntMax
 * IteratorOverOne
 * IteratorSequence
 * JoinedIterator
 * JoinedSequence
 * LazyBidirectionalCollection
 * LazyCollection
 * LazyFilterBidirectionalCollection
 * LazyFilterCollection
 * LazyFilterIndex
 * LazyFilterIterator
 * LazyFilterSequence
 * LazyMapBidirectionalCollection
 * LazyMapCollection
 * LazyMapIterator
 * LazyMapRandomAccessCollection
 * LazyMapSequence
 * LazyRandomAccessCollection
 * LazySequence
 * ManagedBuffer
 * ManagedBufferPointer
 * ManagedProtoBuffer
 * Mirror
 * Mirror.AncestorRepresentation
 * Mirror.DisplayStyle
 * MutableBidirectionalSlice
 * MutableRandomAccessSlice
 * MutableRangeReplaceableBidirectionalSlice
 * MutableRangeReplaceableRandomAccessSlice
 * MutableRangeReplaceableSlice
 * MutableSlice
 * NonObjectiveCBase
 * ObjectIdentifier
 * OpaquePointer
 * Optional
 * PlaygroundQuickLook
 * Process
 * RandomAccessSlice
 * Range
 * RangeReplaceableBidirectionalSlice
 * RangeReplaceableRandomAccessSlice
 * RangeReplaceableSlice
 * Repeated
 * ReversedCollection
 * ReversedIndex
 * ReversedRandomAccessCollection
 * ReversedRandomAccessIndex
 * Set
 * SetIndex
 * SetIterator
 * Slice
 * StaticString
 * StrideThrough
 * StrideThroughIterator
 * StrideTo
 * StrideToIterator
 * String
 * String.CharacterView
 * String.CharacterView.Index
 * String.UTF16View
 * String.UTF16View.Index
 * String.UTF16View.Indices
 * String.UTF8View
 * String.UTF8View.Index
 * String.UnicodeScalarView
 * String.UnicodeScalarView.Index
 * String.UnicodeScalarView.Iterator
 * String.UnicodeScalarView.UnicodeScalarIndex
 * UInt
 * UInt16
 * UInt32
 * UInt64
 * UInt8
 * UTF16
 * UTF32
 * UTF8
 * UnicodeDecodingResult
 * UnicodeScalar
 * Unmanaged
 * UnsafeBufferPointer
 * UnsafeBufferPointerIterator
 * UnsafeMutableBufferPointer
 * UnsafeMutablePointer
 * UnsafePointer
 * Zip2Iterator
 * Zip2Sequence
 */

//: [Next](@next)